version: '{build}'
shallow_clone: true

environment:
  matrix:
    - perl_type: system
    - perl_type: strawberry
    - perl_type: strawberry
      perl_version: 5.12.3.1
    - perl_type: strawberry
      perl_version: 5.16.3.3
    - perl_type: strawberry
      perl_version: 5.20.1.1

install:
  - 'call .appveyor.cmd perl_setup'
  - 'cpan ExtUtils::PL2Bat'
  - '%perl% -V'

build: off

test_script:
  - 'prove -l t'

