svn:
  repository: "https://svn.perl.org/modules/"
  layout:
    trunk: "#DIST#/trunk/"
    tags: "#DIST#/tags/"
    branches: "#DIST#/branches/"
  tag:
    name: "#VERSION#"
    message: "tagging #DIST# release #VERSION#"
not_kwalitee:
  - has_test_pod
  - has_test_pod_coverage
publish:
  pause:
  process:
    - clean
    - create_build --no-sign
    - check_manifest
    - check_changes
    - check_meta_author
    - .test
    #- .testpod
    #- .testpodcoverage
    - .dist
    #- check_kwalitee
    - .disttest
    - check_version_control
  shipit:
    - tag_version_control
    - scp_relay
    - pause_http_relay
