--- #YAML:1.0
name: Sample
version: 0.01
license: perl
distribution_type: module
requires:
  File::Spec: 0
recommends: {}
build_requires: {}
conflicts: {}
provides:
  Sample:
    file: lib/Sample.pm
    version: 0.01
generated_by: Module::Build version 0.19_02
