=head1 Release instructions for Module::Build

=head2 Prerequisites

Recent Module::Build releases have been packaged using the CPDK tool
by Eric Wilhelm.  This distribution is not yet on CPAN, but can be
installed from its repository:

  $ svn co http://scratchcomputing.com/svn/CPDK/trunk/ CPDK
  $ cd CPDK
  $ cpan .

=head2 Packaging and shipping

Update Module::Build and make sure there are no local changes or conflicts.

  $ svn up

  $ svn st

See what the last tag was:

  $ svn_taglist | tail
  ...
  0.31_02

Pull the logs since that tag and update the Changes file if necessary

  $ svn_logsincetag 0.31_02 | less
  ...

  $ vim Changes

If everything is good, just datestamp the version section at the top of
Changes (e.g. use "r! date" then "kJ" in vim.)

  $ svn ci -m "Changes - prep for release"

And we should now be ready for automated shipping:

  $ publish-module

At the moment, for anyone but Eric Wilhelm, this will fail during
the 'scp_relay' stage, but the tarball exists and can be uploaded
to PAUSE using other means.

=head2 After shipping

Now the release is out and tagged.  Start a new version number

  $ ./devtools/bump_version.pl

  $ svn ci -m "Changes, lib/***.pm - bump version"

=cut

